import Head from 'next/head'
import Image from 'next/image'

import Layout from '@/components/Layout'
import {API_URL} from '@/config/index'
import EventItem from '@/components/EventItem'



export default function EventsPage({events}) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className='text-center text-2xl font-bold underline'>Events</h1>
        {events.length === 0 && <h3>No Events to show</h3>}
        {events.map((evt)=>{

          return (
          
          <EventItem key={evt.id} evt={evt}/>
          
          
          
          )
        })}
      </main>
    </Layout>
  )
}


export async function getServerSideProps(){
  const {
    API_URL
  } = process.env

  const res = await fetch(`${API_URL}/api/events?populate=image&?_sort=date:ASC`)
  const events = await res.json()
 
  return{
    props: {
      events: events.data
    }
  }
}